export const actionTypes = {
	LANGUAGE: 'language',
	RESULTS: 'RESULTS',
	TITLE_FROM: 'TITLE_FROM',
	TITLE_TO: 'TITLE_TO',
	AUTOCOMPLETE_ORIGIN: 'AUTOCOMPLETE_ORIGIN',
	AUTOCOMPLETE_DESTINATION: 'AUTOCOMPLETE_DESTINATION',
	ORIGIN: 'ORIGIN',
	DESTINATION: 'DESTINATION'
};
